version: '3.1'

services:

    db:
        image: postgres
        restart: always
        container_name: database
        environment:
            POSTGRES_DB: newdb
            POSTGRES_PASSWORD: password
        volumes:
            - newdb:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        tty: true

    user-service:
        build:
            context: ./user-service
        depends_on:
            - db
        restart: always
        environment:
            POSTGRES_DB: newdb
            POSTGRES_PASSWORD: password
        ports:
            - "8081:8081"


    frontend:
        build:
            context: ./frontend
        depends_on:
            - user-service
        restart: always
        environment:
            POSTGRES_DB: newdb
            POSTGRES_PASSWORD: password
        ports:
            - "8080:8080"

volumes:
    newdb:
